apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
  labels:
    app: my-rc-test-app
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx
  replicas: 4